// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // Single source of truth: seeds knowledge + admin, then connect mock data.
    seed: "npm run seed",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
